# Generated by Django 5.2 on 2025-07-22 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallepedido',
            options={'managed': False, 'verbose_name': 'Detalle de Pedido', 'verbose_name_plural': 'Detalles de Pedido'},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'managed': False, 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
    ]
